sudo: required
services:
  - docker

before_install: 
  - docker builder - devji79/docker-complex -f ./client/Dockerfile.devji79/docker-complex-web ./client

script:
  - docker run -e CI-true devji79/docker-complex-web npm test

after_success: 
  - docker build -t devji79/docker-complex-web-client ./client
  - docker build -t devji79/docker-complex-web-nginx ./nginx
  - docker build -t devji79/docker-complex-web-server ./server
  - docker build -t devji79/docker-complex-web-worker ./worker
